---
- hosts: localhost
  become: yes
  tasks: 
  -  name: create a ansible nodes
     ec2: 
       key_name: myorengaOfflinekey
       instance_type: t2.micro
       image: ami-06d49441f61128762
       wait: yes
       group: MYALL
       count: 2
       region: us-east-2
       vpc_subnet_id: subnet-0c437810b070c3ee9
       assign_public_ip: yes
       instance_tags:
           Name: ansibleNodes

