---
- hosts: 172.31.26.228
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myfirsttaskvar

  - name: i want to display first task result
    debug:
        msg: "{{ myfirsttaskvar }}" 
    