---
- hosts: all
  become: yes
  tasks:
   - name: i want to install git tree and we get by using same task
     apt:
       name: "{{item}}"
       state: present
      loops:
        - git 
        - tree
        - wget