---
- hosts: all
  become: yes
  tasks:
   - name: i want to Install web server on only ubuntu nodes
     apt:
       name: apache2
       state: present
     when: ansible_os_family=="Debian"

   - name: i want to install start webserver on only ubuntu nodes
     service: 
       name: apache2
       state: started
     when: ansible_os_family=="Debian"